### pandas

>panads is power full python library for manipulation arry analysis of data

>its a open source library

>fast(built on top of numpy) , flexible(different resource) , productive library

In [3]:
! pip install pandas

Access is denied.

In [4]:
import pandas as pd

In [5]:
pd.__version__

'2.2.3'

#### Seres - One dimential Array(data structure) with lable

In [6]:
pd.Series([1, 2, 3, 4, 5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [7]:
l1 = [1, 2, 3, 4, 5]
pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [9]:
pd.Series(l1, index=['a', 'b', 'c', 'd', 'e'],name='my_series')

a    1
b    2
c    3
d    4
e    5
Name: my_series, dtype: int64

In [10]:
s = pd.Series(l1, index=['a', 'b', 'c', 'd', 'e'],name='my_series')

In [11]:
s[1]

C:\Users\klemp\AppData\Local\Temp\ipykernel_10464\878419959.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s[1]

np.int64(2)

In [12]:
s['a']

np.int64(1)

In [13]:
type(s)

pandas.core.series.Series

In [14]:
s.index[0]

'a'

In [15]:
s.values

array([1, 2, 3, 4, 5])

> note : index in seres are immutable(can't change)

In [16]:
## Changing the index of pandas Series

s.rename(index={'b':'y'})

a    1
y    2
c    3
d    4
e    5
Name: my_series, dtype: int64

In [17]:
s.rename(index={'b':'y'}, inplace=True)

### DataFrame-  Its a 2nd array (just like tables)

In [18]:
dict1 = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
df = pd.DataFrame(dict1, index=[0])

In [19]:
dict1 = {'Name':['Aditya', 'Kumar', 'Singh', 'Kumar', 'Aditya'],
        'Age':[25, 30, 35, 40, 45],
        'City':['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata']}
print(dict1)

{'Name': ['Aditya', 'Kumar', 'Singh', 'Kumar', 'Aditya'], 'Age': [25, 30, 35, 40, 45], 'City': ['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata']}

In [20]:
pd.DataFrame(dict1, index=[0, 1, 2, 3, 4])

     Name  Age       City
0  Aditya   25      Delhi
1   Kumar   30     Mumbai
2   Singh   35  Bangalore
3   Kumar   40    Chennai
4  Aditya   45    Kolkata

In [21]:
type(df)

pandas.core.frame.DataFrame

In [20]:
df.head(3)

   a  b  c  d  e
0  1  2  3  4  5

In [22]:
dict1 = {'Name':['Aditya', 'Kumar', 'Singh', 'Kumar', 'Aditya'],
        'Age':[25, 30, 35, 40, 45],
        'City':['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata']}
print(dict1)

{'Name': ['Aditya', 'Kumar', 'Singh', 'Kumar', 'Aditya'], 'Age': [25, 30, 35, 40, 45], 'City': ['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata']}

In [24]:
pd.DataFrame(dict1, index=[0, 1, 2, 3, 4])

     Name  Age       City
0  Aditya   25      Delhi
1   Kumar   30     Mumbai
2   Singh   35  Bangalore
3   Kumar   40    Chennai
4  Aditya   45    Kolkata

In [22]:
df.head(3)

   a  b  c  d  e
0  1  2  3  4  5

In [23]:
df.tail(3)

   a  b  c  d  e
0  1  2  3  4  5

In [24]:
len(df)

1

In [25]:
dict1 = {'Name':['Aditya', 'Kumar', 'Singh', 'Kumar', 'Aditya'],
        'Age':[25, 30, 35, 40, 45],
        'City':['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata'],
        'Salary':[50000, 60000, 70000, 80000, 90000],
        'Experience':[2, 5, 8, 10, 12]}

In [26]:
pd.DataFrame(dict1, index=[0, 1, 2, 3, 4])

     Name  Age       City  Salary  Experience
0  Aditya   25      Delhi   50000           2
1   Kumar   30     Mumbai   60000           5
2   Singh   35  Bangalore   70000           8
3   Kumar   40    Chennai   80000          10
4  Aditya   45    Kolkata   90000          12

In [26]:
df.count()

a    1
b    1
c    1
d    1
e    1
dtype: int64

In [27]:
df = dict1 = {'Name':['Aditya', 'Kumar', 'Singh', 'Kumar', 'Aditya'],
        'Age':[25, 30, 35, 40, 45],
        'City':['Delhi', 'Mumbai', 'Bangalore', 'Chennai', 'Kolkata'],
        'Salary':[50000, 60000, 70000, 80000, 90000],
        'Experience':[2, 5, 8, 10, 12]}

In [28]:
type(df)

dict

In [29]:
df['Name']

['Aditya', 'Kumar', 'Singh', 'Kumar', 'Aditya']

In [31]:
df ['Experience']

[2, 5, 8, 10, 12]

### basic operation

>importing data set from different files
>Importing tabular dataset

In [30]:
pd.DataFrame(df, index=[0, 1, 2, 3, 4])

     Name  Age       City  Salary  Experience
0  Aditya   25      Delhi   50000           2
1   Kumar   30     Mumbai   60000           5
2   Singh   35  Bangalore   70000           8
3   Kumar   40    Chennai   80000          10
4  Aditya   45    Kolkata   90000          12

In [31]:
pd.read_csv(r'C:\Users\klemp\OneDrive\Documents\aditya vs\datasets (1)\ETH_1h.csv')

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [32]:
stock_df = pd.read_csv(r'C:\Users\klemp\OneDrive\Documents\aditya vs\datasets (1)\ETH_1h.csv')

In [33]:
stock_df = pd.DataFrame(stock_df)

In [34]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [35]:
len(stock_df)

23674

In [36]:
stock_df.head(3)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81

In [37]:
stock_df.tail()

                   Date  Symbol    Open    High    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.1  275.01   679358.87

In [38]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [39]:
stock_df['High'] > stock_df['Low']

0        True
1        True
2        True
3        True
4        True
         ...
23669    True
23670    True
23671    True
23672    True
23673    True
Length: 23674, dtype: bool

In [40]:
stock_df[['Open','Close','Volume']]

         Open   Close      Volume
0      129.94  128.71  1940673.93
1      119.51  129.94  7579741.09
2      124.47  119.51  4898735.81
3      124.08  124.47  2753450.92
4      124.85  124.08  4461424.71
...       ...     ...         ...
23669  265.74  272.57  1500282.55
23670  268.79  265.74  1702536.85
23671  274.83  268.79  3010787.99
23672  275.01  274.83   824362.87
23673  279.98  275.01   679358.87

[23674 rows x 3 columns]

In [42]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [43]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [44]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [45]:
stock_df.loc[23672]

Date      2017-07-01 12-PM
Symbol              ETHUSD
Open                275.01
High                275.01
Low                  271.0
Close               274.83
Volume           824362.87
Name: 23672, dtype: object

In [51]:
stock_df.loc[23672,['Data','Close','Open']]

KeyError: "['Data'] not in index"

In [49]:
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

##Slicing in loc(Labeled Location)

In [45]:
stock_df.loc[23672,'Open':'Close']

Open     275.01
High     275.01
Low       271.0
Close    274.83
Name: 23672, dtype: object

In [50]:
stock_df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [47]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [48]:
stock_df.iloc[2,2]

np.float64(124.47)

In [50]:
stock_df.iloc[1,2]

np.float64(119.51)

In [51]:
stock_df.iloc[3,[2,4]]

Open    124.08
Low     121.63
Name: 3, dtype: object

In [52]:
stock_df.iloc[2,2:6]

Open     124.47
High     124.85
Low       115.5
Close    119.51
Name: 2, dtype: object

Filtering

In [54]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [55]:
stock_df['High']

0        131.82
1        132.02
2        124.85
3        127.42
4        129.51
          ...
23669    272.74
23670    269.90
23671    274.93
23672    275.01
23673    279.99
Name: High, Length: 23674, dtype: float64

In [57]:
f1 = stock_df['High']>130

stock_gt_130 = stock_df[f1]

In [58]:
stock_gt_130 = stock_df[f1]

In [59]:
stock_gt_130.reset_index(drop=True, inplace=True)

In [60]:
stock_gt_130

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
3      2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
4      2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
...                 ...     ...     ...     ...     ...     ...         ...
21608  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
21609  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
21610  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
21611  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
21612  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[21613 rows x 7 columns]

##Adding new coloumn

In [61]:
len(stock_df)

23674

In [62]:
stock_df.iloc[len(stock_df)-1]

Date      2017-07-01 11-AM
Symbol              ETHUSD
Open                279.98
High                279.99
Low                  272.1
Close               275.01
Volume           679358.87
Name: 23673, dtype: object

In [63]:
stock_df['Random_col'] = list(range(1, len(stock_df)+1))

In [65]:
stock_df

,Date,Symbol,Open,High,Low,Close,Volume,Random_col
0,2020-03-13 08-PM,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,1
1,2020-03-13 07-PM,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,2
2,2020-03-13 06-PM,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,3
3,2020-03-13 05-PM,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,4
4,2020-03-13 04-PM,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,5
...,...,...,...,...,...,...,...,...
23669,2017-07-01 03-PM,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,23670
23670,2017-07-01 02-PM,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,23671
23671,2017-07-01 01-PM,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,23672
23672,2017-07-01 12-PM,ETHUSD,275.01,275.01,271.00,274.83,824362.87,23673
23673,2017-07-01 11-AM,ETHUSD,279.98,279.99,272.10,275.01,679358.87,23674

In [66]:
stock_df.drop(columns=['Random_col'], inplace=True)

In [67]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [68]:
stock_df.drop(23672, axis=0, inplace=True)

In [69]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23668  2017-07-01 04-PM  ETHUSD  272.57  272.57  267.60  268.00  1287300.75
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23673 rows x 7 columns]

In [70]:
a = 12
n = 32
print(a+n)

44